//! Built-in Herdr actions shown by the palette.

use serde_json::{json, Value};

fn action(
    id: &str,
    title: &str,
    description: &str,
    icon: &str,
    shortcut: &str,
    argv: &[&str],
) -> Value {
    json!({"id":id,"title":title,"category":"Actions","description":description,"icon":icon,"aliases":[],"shortcuts":if shortcut.is_empty(){vec![]}else{vec![shortcut]},"invocation":{"kind":"herdr","argv":argv}})
}
#[allow(clippy::too_many_arguments)]
fn resolve(
    id: &str,
    title: &str,
    description: &str,
    icon: &str,
    shortcut: &str,
    name: &str,
    step: Option<i32>,
    prompt: Option<&str>,
) -> Value {
    let mut item = json!({"id":id,"title":title,"category":"Actions","description":description,"icon":icon,"aliases":[],"shortcuts":if shortcut.is_empty(){vec![]}else{vec![shortcut]},"invocation":{"kind":"resolve","action":name}});
    if let Some(step) = step {
        item["invocation"]["step"] = json!(step);
    }
    if let Some(placeholder) = prompt {
        item["prompt"] = json!({"placeholder":placeholder});
    }
    item
}

/// Static action rows. Live workspaces, tabs and panes are supplied by the backend.
pub fn default_items() -> Vec<Value> {
    vec![
        action(
            "new_workspace",
            "New workspace",
            "Create and focus a workspace",
            "◇",
            "prefix+shift+n",
            &["workspace", "create", "--focus"],
        ),
        resolve(
            "rename_workspace",
            "Rename workspace",
            "Rename the current workspace",
            "◇",
            "prefix+shift+w",
            "rename-workspace",
            None,
            Some("New name"),
        ),
        resolve(
            "close_workspace",
            "Close workspace",
            "Close the current workspace",
            "×",
            "prefix+shift+d",
            "close-workspace",
            None,
            None,
        ),
        resolve(
            "previous_workspace",
            "Previous workspace",
            "Focus the previous workspace",
            "←",
            "",
            "focus-workspace",
            Some(-1),
            None,
        ),
        resolve(
            "next_workspace",
            "Next workspace",
            "Focus the next workspace",
            "→",
            "",
            "focus-workspace",
            Some(1),
            None,
        ),
        resolve(
            "new_tab",
            "New tab",
            "Create and focus a tab in the current workspace",
            "▣",
            "prefix+c",
            "create-tab",
            None,
            None,
        ),
        resolve(
            "rename_tab",
            "Rename tab",
            "Rename the current tab",
            "▣",
            "prefix+shift+t",
            "rename-tab",
            None,
            Some("New name"),
        ),
        resolve(
            "previous_tab",
            "Previous tab",
            "Focus the previous tab",
            "←",
            "prefix+p",
            "focus-tab",
            Some(-1),
            None,
        ),
        resolve(
            "next_tab",
            "Next tab",
            "Focus the next tab",
            "→",
            "prefix+n",
            "focus-tab",
            Some(1),
            None,
        ),
        resolve(
            "close_tab",
            "Close tab",
            "Close the current tab",
            "×",
            "prefix+shift+x",
            "close-tab",
            None,
            None,
        ),
        action(
            "focus_pane_left",
            "Focus pane left",
            "Focus the pane to the left",
            "←",
            "prefix+h",
            &["pane", "focus", "--direction", "left", "--current"],
        ),
        action(
            "focus_pane_down",
            "Focus pane down",
            "Focus the pane below",
            "↓",
            "prefix+j",
            &["pane", "focus", "--direction", "down", "--current"],
        ),
        action(
            "focus_pane_up",
            "Focus pane up",
            "Focus the pane above",
            "↑",
            "prefix+k",
            &["pane", "focus", "--direction", "up", "--current"],
        ),
        action(
            "focus_pane_right",
            "Focus pane right",
            "Focus the pane to the right",
            "→",
            "prefix+l",
            &["pane", "focus", "--direction", "right", "--current"],
        ),
        action(
            "split_vertical",
            "Split pane right",
            "Split the current pane side by side",
            "▯",
            "prefix+v",
            &[
                "pane",
                "split",
                "--current",
                "--direction",
                "right",
                "--focus",
            ],
        ),
        action(
            "split_horizontal",
            "Split pane down",
            "Split the current pane stacked",
            "▤",
            "prefix+minus",
            &[
                "pane",
                "split",
                "--current",
                "--direction",
                "down",
                "--focus",
            ],
        ),
        action(
            "zoom",
            "Zoom pane",
            "Toggle focused pane zoom",
            "◲",
            "prefix+z",
            &["pane", "zoom", "--current"],
        ),
        resolve(
            "rename_pane",
            "Rename pane",
            "Rename the current pane",
            "▭",
            "prefix+shift+p",
            "rename-pane",
            None,
            Some("New name"),
        ),
        resolve(
            "clear_pane_name",
            "Clear pane name",
            "Remove the current pane's custom name",
            "▭",
            "",
            "rename-pane-clear",
            None,
            None,
        ),
        action(
            "resize_pane_left",
            "Resize pane left",
            "Grow the pane toward the left",
            "←",
            "",
            &["pane", "resize", "--direction", "left", "--current"],
        ),
        action(
            "resize_pane_down",
            "Resize pane down",
            "Grow the pane toward the bottom",
            "↓",
            "",
            &["pane", "resize", "--direction", "down", "--current"],
        ),
        action(
            "resize_pane_up",
            "Resize pane up",
            "Grow the pane toward the top",
            "↑",
            "",
            &["pane", "resize", "--direction", "up", "--current"],
        ),
        action(
            "resize_pane_right",
            "Resize pane right",
            "Grow the pane toward the right",
            "→",
            "",
            &["pane", "resize", "--direction", "right", "--current"],
        ),
        action(
            "swap_pane_left",
            "Swap pane left",
            "Swap with the pane to the left",
            "←",
            "",
            &["pane", "swap", "--direction", "left", "--current"],
        ),
        action(
            "swap_pane_down",
            "Swap pane down",
            "Swap with the pane below",
            "↓",
            "",
            &["pane", "swap", "--direction", "down", "--current"],
        ),
        action(
            "swap_pane_up",
            "Swap pane up",
            "Swap with the pane above",
            "↑",
            "",
            &["pane", "swap", "--direction", "up", "--current"],
        ),
        action(
            "swap_pane_right",
            "Swap pane right",
            "Swap with the pane to the right",
            "→",
            "",
            &["pane", "swap", "--direction", "right", "--current"],
        ),
        resolve(
            "move_pane_new_tab",
            "Move pane to new tab",
            "Move the current pane into a new tab",
            "▣",
            "",
            "move-pane-new-tab",
            None,
            None,
        ),
        resolve(
            "move_pane_new_workspace",
            "Move pane to new workspace",
            "Move the current pane into a new workspace",
            "◇",
            "",
            "move-pane-new-workspace",
            None,
            None,
        ),
        resolve(
            "close_pane",
            "Close pane",
            "Close the focused pane",
            "×",
            "prefix+x",
            "close-pane",
            None,
            None,
        ),
        resolve(
            "new_worktree",
            "New worktree",
            "Create and open a Git worktree; leave blank for automatic naming",
            "◈",
            "prefix+shift+g",
            "worktree-create",
            None,
            Some("Branch name (leave blank for automatic)"),
        ),
        resolve(
            "open_worktree",
            "Open worktree",
            "Open an existing Git worktree by branch or path",
            "◈",
            "",
            "worktree-open",
            None,
            Some("Branch or path (use ./ for relative paths)"),
        ),
        resolve(
            "remove_worktree",
            "Remove worktree",
            "Remove the current workspace worktree checkout",
            "×",
            "",
            "worktree-remove",
            None,
            Some("Type \"yes\" to confirm"),
        ),
        resolve(
            "previous_agent",
            "Previous agent",
            "Focus the previous agent",
            "←",
            "",
            "focus-agent",
            Some(-1),
            None,
        ),
        resolve(
            "next_agent",
            "Next agent",
            "Focus the next agent",
            "→",
            "",
            "focus-agent",
            Some(1),
            None,
        ),
        {
            let mut item = resolve(
                "edit_scrollback",
                "Edit scrollback",
                "Open pane terminal history in your editor",
                "▤",
                "prefix+e",
                "",
                None,
                None,
            );
            item["invocation"] = json!({"kind":"pane-api","method":"pane.edit_scrollback"});
            item["aliases"] = json!(["terminal history", "editor"]);
            item
        },
    ]
}
